-- أسر قريبة | Supabase schema (production-oriented)
-- Run this script in Supabase SQL Editor.

create extension if not exists "uuid-ossp";

-- Profiles table linked to auth.users
create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  email text unique,
  role text not null default 'user' check (role in ('user', 'business')),
  created_at timestamptz not null default now()
);

create table if not exists public.businesses (
  id bigint generated by default as identity primary key,
  owner_id uuid not null unique references public.users(id) on delete cascade,
  name text not null,
  category text not null,
  description text,
  lat double precision,
  lng double precision,
  phone text,
  instagram text,
  rating numeric(3,2) not null default 4.50,
  logo_url text,
  cover_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  name text not null,
  price numeric(10,2) not null default 0,
  image text,
  created_at timestamptz not null default now()
);

create table if not exists public.favorites (
  user_id uuid not null references public.users(id) on delete cascade,
  business_id bigint not null references public.businesses(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, business_id)
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  business_id bigint references public.businesses(id) on delete cascade,
  user_id uuid references public.users(id) on delete set null,
  event_type text not null check (event_type in ('view', 'click', 'favorite')),
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_businesses_category on public.businesses(category);
create index if not exists idx_products_business_id on public.products(business_id);
create index if not exists idx_events_business_created_at on public.analytics_events(business_id, created_at);

-- Auto-create profile row after auth signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, name, email, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', ''),
    new.email,
    coalesce(new.raw_user_meta_data ->> 'role', 'user')
  )
  on conflict (id) do update
    set name = excluded.name,
        email = excluded.email,
        role = excluded.role;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Analytics aggregate function for dashboard
create or replace function public.business_overview(p_business_id bigint)
returns table (views bigint, clicks bigint, favorites bigint)
language sql
security definer
as $$
  select
    coalesce(sum(case when event_type = 'view' then 1 else 0 end), 0)::bigint as views,
    coalesce(sum(case when event_type = 'click' then 1 else 0 end), 0)::bigint as clicks,
    (select count(*)::bigint from public.favorites f where f.business_id = p_business_id) as favorites
  from public.analytics_events e
  where e.business_id = p_business_id;
$$;

-- RLS
alter table public.users enable row level security;
alter table public.businesses enable row level security;
alter table public.products enable row level security;
alter table public.favorites enable row level security;
alter table public.analytics_events enable row level security;

-- Users policies
create policy "users_select_own" on public.users for select using (auth.uid() = id);
create policy "users_update_own" on public.users for update using (auth.uid() = id);
create policy "users_insert_own" on public.users for insert with check (auth.uid() = id);

-- Businesses policies
create policy "businesses_public_read" on public.businesses for select using (true);
create policy "businesses_owner_insert" on public.businesses for insert with check (auth.uid() = owner_id);
create policy "businesses_owner_update" on public.businesses for update using (auth.uid() = owner_id);
create policy "businesses_owner_delete" on public.businesses for delete using (auth.uid() = owner_id);

-- Products policies
create policy "products_public_read" on public.products for select using (true);
create policy "products_owner_insert" on public.products
for insert with check (
  exists (
    select 1 from public.businesses b
    where b.id = business_id and b.owner_id = auth.uid()
  )
);
create policy "products_owner_update" on public.products
for update using (
  exists (
    select 1 from public.businesses b
    where b.id = business_id and b.owner_id = auth.uid()
  )
);
create policy "products_owner_delete" on public.products
for delete using (
  exists (
    select 1 from public.businesses b
    where b.id = business_id and b.owner_id = auth.uid()
  )
);

-- Favorites policies
create policy "favorites_read_own" on public.favorites for select using (auth.uid() = user_id);
create policy "favorites_write_own" on public.favorites for insert with check (auth.uid() = user_id);
create policy "favorites_delete_own" on public.favorites for delete using (auth.uid() = user_id);

-- Analytics policies
create policy "analytics_insert_authenticated" on public.analytics_events
for insert with check (auth.role() = 'authenticated');
create policy "analytics_read_owner_only" on public.analytics_events
for select using (
  exists (
    select 1 from public.businesses b
    where b.id = business_id and b.owner_id = auth.uid()
  )
);

-- Storage setup (run once)
insert into storage.buckets (id, name, public)
values ('business-media', 'business-media', true)
on conflict (id) do nothing;

create policy "public_read_business_media"
on storage.objects for select
using (bucket_id = 'business-media');

create policy "owner_upload_business_media"
on storage.objects for insert
with check (
  bucket_id = 'business-media'
  and auth.role() = 'authenticated'
);

create policy "owner_update_business_media"
on storage.objects for update
using (
  bucket_id = 'business-media'
  and auth.role() = 'authenticated'
);

create policy "owner_delete_business_media"
on storage.objects for delete
using (
  bucket_id = 'business-media'
  and auth.role() = 'authenticated'
);
